// src/blog/ListPage.svelte
<script lang="ts">
  import AboutMe from '../shared/AboutMe.svelte';
  import Link from '../shared/Link.svelte';
  import { posts } from './shared/data';
</script>

<div class="container">
  <h1>Blog</h1>
  <ul class="posts-list">
    {#each posts as post}
      <li>
        <div class="post">
          <Link href="/blog/{post.url}">{post.title}</Link>
          <span>{post.summary}</span>
        </div>
      </li>
    {/each}
  </ul>
  <AboutMe />
</div>

<style lang="scss">
  @use '../style/common.scss';

  .container {
    @extend %flex-column;
    border: 2px solid #ddd;
    border-radius: var(--border-radius);
    margin-top: 16px;
    padding: 12px;
    width: 800px;
  }

  .posts-list {
    @extend %flex-row;
    margin-left: 16px;
    margin-bottom: 16px;
  }

  .post {
    @extend %flex-column;
  }
</style>

// src/blog/ListPage.tsx
import { create, props } from '@stylexjs/stylex';
import { Link } from 'react-router-dom';
import { commonStyles } from '../common.stylex';
import { posts } from './shared/data';
import type { IPost } from './shared/model';

function postUrl(post: IPost) {
  return '/blog/' + post.url;
}

export function ListPage() {
  return (
    <div {...props(styles.list)}>
      <h1 {...props(commonStyles.h1)}>Blog</h1>
      <ul {...props(styles.item)}>
        {posts.map((post) => (
          <li key={post.url}>
            <div {...props(styles.description)}>
              <Link to={postUrl(post)}>{post.title}</Link>
              <span>{post.summary}</span>
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
}

const styles = create({
  list: {
    border: '2px solid #ddd',
    borderRadius: '4px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    marginTop: '16px',
    padding: '12px',
    width: '800px',
  },
  item: {
    display: 'flex',
    flexDirection: 'row',
    gap: '8px',
    marginBottom: '16px',
    marginLeft: '16px',
  },
  description: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
});
